#!/bin/sh
source ./.aosbuild

aos_compiler ${CC:-clang}
aos_cflags -march=native -std=c11 -Os -pipe -Wall -Wextra -Werror -pedantic -fPIC
aos_lflags $CFLAGS -shared
aos_bin libagl.so
aos_src src/*.c

aos_main $@
